<form class="generic-form" action="edit_post.php" method="POST">
        <h2><i class="fas fa-pen"></i>   Editer le profil</h2>
            <fieldset>
                <legend><i class="far fa-file"></i> Données personnelles</legend>
                <ul>
                <?php foreach($user as $value) { ?>
                    <li>
                        <label for="lastName">Nom :</label>
                        <input type="text" id="lastname" name="lastname" value="<?= $value['lastname']?>">
                    </li>
                    <li>
                        <label class="textarea" for="firstname">Prénom :</label>
                        <input type="text" id="firstname" name="firstname" value="<?= $value['firstname']?>">
                    </li>
                    <?php } ?> 
                    <li>
                        <label for="address">Adresse :</label>
                        <input type="text" id="address" name="address" value="">
                    </li>
                    <li>
                        <label class="textarea" for="zip">Code Postal :</label>
                        <input type="text" id="zip" name="zip" value="">
                    </li>
                    <li>
                        <label class="textarea" for="city">Ville :</label>
                        <input type="text" id="city" name="city" value="">
                    </li>
                    <li>
                        <button class="button button-primary" type="submit" name="maj">Mettre à jour</button>
                        <button class="button button-cancel" href="index.php">Annuler</button>
                    </li>
                </ul>
            </fieldset>
        </form>