<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>SmoothMaker</title>
	<!-- Appel CSS -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
<link href="https://fonts.googleapis.com/css?family=Amatic+SC|Open+Sans" rel="stylesheet">
<!-- 	<link rel="stylesheet" href="css/normalize.css"> -->
<!-- bootstrap -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="style.css">
</head>

<body>
	<!--HEADER-->
	<header>

        
		<nav id="navPageUser" class="d-flex bd-highlight">
        <div class="p-2 w-100 bd-highlight">
            <img id="logoPageUser" src="images/logo-degrade.png"/>
			<a class="expand" href="index.html">Home</a>
            <a class="expand" href="produits.html">Produits</a>
            <a class="expand" href="recettes.html">Recettes</a>
            <a class="expand" href="contact.html">Contact</a>
        </div> 
        <div class="p-2 flex-shrink-1 bd-highlight">
			<a class="expand"  href="login.html"><i class="far fa-user-circle connect"></i></a>
        </div>
        </nav>
        <section id="pseudoAvatar">
            <div class="pseudoAvatar">
                <h1>@Pseudo-User</h1>
                <img id="avatar" src="images/3smooth.jpg" width="300" height="300" />
            </div>
        </section>
	</header>
	<!--MAIN CONTENT-->

<main>
<section id="">
		<article class="panelUser row">
			<div id="informations" class="col-5">
                <h2 class="titleinfo">Informations</h2>
                    <!-- <?php foreach($user as $value) { ?> -->
                    <h3 class="info" style="display:inline">Nom</h3>
                        <!-- <p><?= $value['lastname']?></p> -->
                    <h3 class="info">Prénom</h3>
                        <!-- <p><?= $value['firstname']?></p> -->
                    <h3 class="info">Anniversaire</h3>
                        <!-- <p><?= $value['titre']?></p> -->
                    <h3 class="info">Adresse</h3>
                        <!-- <p><?= $value['address']?></p> -->
                    <h3 class="info">Code Postal</h3>
                        <!-- <p><?= $value['zip']?></p> -->
                    <h3 class="info">Ville</h3>
                        <!-- <p><?= $value['city']?></p> -->
                    <h3 class="info">Email</h3>
                        <p>Bestotodu38@gmail.com</p>
                    <h3 class="info">Date d'inscription</h3>
                        <p>15/10/2017</p>
                    <!-- <?php } ?>  -->
                <small>
                    <a href="">Modifier mes informations</a>
                </small>
			</div>
			<div id="favorites" class="col-5">
                <h2 class="row">Mes recettes favorites :</h2>
                <img id="" src="images/smoothie2.jpg" class="rounded-circle" width="140" height="140"/>
                <img id="" src="images/smoothie2.jpg" class="rounded-circle" width="140" height="140"/>
                <img id="" src="images/smoothie2.jpg" class="rounded-circle" width="140" height="140"/>
                <img id="" src="images/smoothie2.jpg" class="rounded-circle" width="140" height="140"/>
                <img id="" src="images/smoothie2.jpg" class="rounded-circle" width="140" height="140"/>
                <img id="" src="images/smoothie2.jpg" class="rounded-circle" width="140" height="140"/>
                <img id="" src="images/smoothie2.jpg" class="rounded-circle" width="140" height="140"/>
                <img id="" src="images/smoothie2.jpg" class="rounded-circle" width="140" height="140"/>
                <img id="" src="images/smoothie2.jpg" class="rounded-circle" width="140" height="140"/>
			</div>
		</article>
</section>
	</main>
	<footer>
	<small id="licence">
		<div class="reseau">
			<a href="#"><img id="logo2" src="images/instagram.svg"/></a>
			<a href="#"><img id="logo2" src="images/twitter.svg"/></a>
			<a href="#"><img id="logo2" src="images/facebook.svg"/></a>
		</div>

<nav>
			<a class="expand" href="index.html">Home</a>
			<a class="expand" href="#">Produits</a>
			<a class="expand" href="#">Recettes</a>
			<a class="expand" href="#">Contact</a>
</nav>
<p>2019 ©LeMeilleurGroupeDeLaClasse</p>
	</small>
</footer>
</div>
<script src="main.js"></script>
</body>
</html>